version: '3.8'

services:
  orchestrator:
    build:
      context: ./orchestrator_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PDF_SERVICE_URL=http://pdf:8001
      - SENTIMENT_SERVICE_URL=http://sentiment:8002
      - CHATBOT_SERVICE_URL=http://chatbot:8003
      - SCRAPER_SERVICE_URL=http://scraper:8004
      - VECTOR_DB_URL=http://vector_db:8005
    depends_on:
      - pdf
      - sentiment
      - chatbot
      - scraper
      - vector_db
      - rabbitmq

  pdf:
    build:
      context: ./pdf_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  sentiment:
    build:
      context: ./sentiment_service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  chatbot:
    build:
      context: ./chatbot_service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - VECTOR_DB_URL=http://vector_db:8005

  scraper:
    build:
      context: ./scraper_service
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  vector_db:
    build:
      context: ./vector_db_service
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    volumes:
      - vector_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  vector_data: