version: '3.8'

services:
  # Base image build
  base:
    build:
      context: .
      dockerfile: docker/base.Dockerfile
    image: umbrella-ai-base:latest

  # PDF Extraction Service
  pdf_extraction:
    build:
      context: .
      dockerfile: docker/pdf_extraction.Dockerfile
    ports:
      - "8001:8001"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./data:/app/data
    depends_on:
      - base
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Sentiment Analysis Service
  sentiment_analysis:
    build:
      context: .
      dockerfile: docker/sentiment_analysis.Dockerfile
    ports:
      - "8002:8002"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - base
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # RAG Scraper Service
  rag_scraper:
    build:
      context: .
      dockerfile: docker/rag_scraper.Dockerfile
    ports:
      - "8003:8003"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - base
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Chatbot Service
  chatbot:
    build:
      context: .
      dockerfile: docker/chatbot.Dockerfile
    ports:
      - "8004:8004"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - base
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Main API Gateway
  api_gateway:
    build:
      context: .
      dockerfile: docker/api_gateway.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    depends_on:
      - pdf_extraction
      - sentiment_analysis
      - rag_scraper
      - chatbot
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    name: umbrella-ai-network
    driver: bridge

volumes:
  data:
    name: umbrella-ai-data