global:
  resolve_timeout: 5m
  slack_api_url: '${SLACK_WEBHOOK_URL}'
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@umbrella-ai.com'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_AUTH_PASSWORD}'

route:
  group_by: ['alertname', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning
      receiver: 'warning-alerts'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#monitoring'
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        send_resolved: true

  - name: 'critical-alerts'
    slack_configs:
      - channel: '#critical-alerts'
        title: '[CRITICAL] {{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        send_resolved: true
    email_configs:
      - to: 'oncall@umbrella-ai.com'
        subject: '[CRITICAL] {{ template "email.subject" . }}'
        html: '{{ template "email.html" . }}'
        send_resolved: true

  - name: 'warning-alerts'
    slack_configs:
      - channel: '#warnings'
        title: '[WARNING] {{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        send_resolved: true

templates:
  - '/etc/alertmanager/templates/*.tmpl' 