global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'umbrella-ai'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'pdf-extraction:8000'
        - 'sentiment-analysis:8001'
        - 'chatbot:8002'
        - 'rag-scraper:8003'
        - 'recommendation:8004'
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        regex: '(.*):.*'
        replacement: '$1' 