name: UMBRELLA-AI Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-html pytest-cov pytest-metadata pytest-timeout
        
    - name: Run tests with coverage
      run: |
        pytest tests/e2e/ \
          --html=reports/test-report.html \
          --self-contained-html \
          --cov=src \
          --cov-report=xml \
          --cov-report=html \
          -v
      env:
        PYTHONPATH: ${{ github.workspace }}
        
    - name: Upload test report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-report
        path: reports/test-report.html
        
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: coverage-report
        path: htmlcov/
        
    - name: Coverage report to PR comment
      uses: codecov/codecov-action@v3
      with:
        file: coverage.xml
        fail_ci_if_error: true
        
    - name: Slack notification
      uses: 8398a7/action-slack@v3
      if: always()
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 